apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  {{ if eq .Values.version "v1" }}
  type: NodePort
  {{ end }}
  ports:
    - name: "vote-service"
      port: 80
      targetPort: 80
      {{ if eq .Values.version "v1" }}
      nodePort: 31000
      {{ end }}
  selector:
    app: vote
